### BCLOUD: PLEASE DO NOT DELETE THE FILE
#<cvspath_svn>,<cvspath_git>,trunk/<branch-name>/-,<revision>,<tag-name>/-,disbuild/-,DEP-<N>,is_git,stable/unstable/-
baidu/goodcoder/liuyuan21,,master,1d5fc68b75dc5cd3220e2813b9e894a088237f0e,
    third-64/boost,baidu/third-party/boost,boost_1-70-0,2a74429018e034f85bf44f0375da050c5deea28d,,,DEP-1,True,unstable
    third-64/gtest,baidu/third-party/gtest,v1.8,e9d10e48145cc907d912685b9664c9d9c514af1b,,,DEP-1,True,unstable
    third-64/glog,baidu/third-party/glog,,,glog_0.4.0-baidu-ee-common_0-4-0-0_GEN_PD_BL,,DEP-1,True,stable
