.SILENT:

#
#makefile-self location, must be always on the top!!!
#
MAKEFILE_PATH_BAIDU_THIRD-PARTY_GTEST := $(word $(words $(MAKEFILE_LIST)), $(MAKEFILE_LIST))
MAKEFILE_DIR_BAIDU_THIRD-PARTY_GTEST := $(shell cd $(dir $(MAKEFILE_PATH_BAIDU_THIRD-PARTY_GTEST)) && pwd)

MAKEFILE_BAIDU_THIRD-PARTY_GTEST := 'imported'

#
#Global Configs
#
WORK_ROOT := $(shell cd $(MAKEFILE_DIR_BAIDU_THIRD-PARTY_GTEST)/../../../.. && pwd)
GCC_PATH := /opt/compiler/gcc-4.8.2/bin

#
#import global configs
#
ifneq ($(MAKEFILE_CONFIG), 'imported')
    include $(MAKEFILE_DIR_BAIDU_THIRD-PARTY_GTEST)/makefile.config
endif

baidu/third-party/gtest_deps:\
		$(WORK_ROOT)/bc_out/baidu/third-party/gtest/output/lib/libgtest.a\
		$(WORK_ROOT)/bc_out/baidu/third-party/gtest/output/lib/libgtest_main.a\

$(WORK_ROOT)/bc_out/baidu/third-party/gtest/output/lib/libgtest.a:$(WORK_ROOT)/baidu/third-party/gtest/lib/libgtest.a 
	$(eval cd_cmd = cd $(WORK_ROOT))
	$(eval mk_cmd = mkdir -p $(WORK_ROOT)/bc_out/baidu/third-party/gtest/output/lib)
	$(eval gcc_cmd = \
	cp \
		-f \
		baidu/third-party/gtest/lib/libgtest.a \
		bc_out/baidu/third-party/gtest/output/lib/libgtest.a)
	$(call exec_cmd, $(cd_cmd));\
	$(call exec_cmd, $(mk_cmd));\
	$(call exec_cmd, $(gcc_cmd))

	echo -e '\033[32m[OK]\033[0m $$WORK_ROOT/bc_out/baidu/third-party/gtest/output/lib/libgtest.a'

$(WORK_ROOT)/bc_out/baidu/third-party/gtest/output/lib/libgtest_main.a:$(WORK_ROOT)/baidu/third-party/gtest/lib/libgtest_main.a 
	$(eval cd_cmd = cd $(WORK_ROOT))
	$(eval mk_cmd = mkdir -p $(WORK_ROOT)/bc_out/baidu/third-party/gtest/output/lib)
	$(eval gcc_cmd = \
	cp \
		-f \
		baidu/third-party/gtest/lib/libgtest_main.a \
		bc_out/baidu/third-party/gtest/output/lib/libgtest_main.a)
	$(call exec_cmd, $(cd_cmd));\
	$(call exec_cmd, $(mk_cmd));\
	$(call exec_cmd, $(gcc_cmd))

	echo -e '\033[32m[OK]\033[0m $$WORK_ROOT/bc_out/baidu/third-party/gtest/output/lib/libgtest_main.a'



#
#import dependency modules
#
