MAKEFILE_CONFIG = 'imported'

#
#Global Functions
#
define exec_cmd
	$(1); if [ $$? -ne 0 ]; then echo 'Error command is: $(1)'; exit 1; fi
endef

define exec_long_cmd
	$(1); if [ $$? -ne 0 ]; then echo -e '\n[Error:6054] Run command error, the command(for debug) has been saved into$(2)';echo -e 'How to fix:';echo -e '        http://wenda.baidu.com/ask/question/57496';exit 1; fi
endef

define save_cmd
	echo $(1) > $(2); if [ $$? -ne 0 ]; then echo save cmd to $(2) failed; exit 1; fi
endef
